### ISSUE TITLE
Menu not showing on mobile devices

### ISSUE THREAD

**Issue by trevordmiller** [Keats/book#15]
It seems that clicking the menu changes classnames but doesn't alter the visual output. There doesn't seem to be a way to access the menu on mobile devices.

Before menu click:

<img width="894" alt="image" src="https://user-images.githubusercontent.com/5497885/86058589-6127b980-ba1e-11ea-8edc-bc501ebb73d2.png">

After menu click:

<img width="954" alt="image" src="https://user-images.githubusercontent.com/5497885/86058608-6a188b00-ba1e-11ea-8f8b-592b8167d3e5.png">

**Comment by skorokithakis** [comment]
This is still an issue 6 months later. Is this theme abandoned?

**Comment by Keats** [comment]
It's not abandoned but I don't see every issue. https://github.com/getzola/book/pull/17

**Comment by skorokithakis** [comment]
I see, thanks.
